all:
	gcc -O3 -march=native -fopt-info-vec-optimized -I/home/lorien/Repos/dynamorio/build/include tests.c -L/home/lorien/Repos/dynamorio/build/lib64/release -ldynamorio /home/lorien/Repos/dynamorio/build/lib64/libdrlibc.a -o tests
